default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  database: backend_development
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  database: backend_test
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV["DB_PASSWORD"] %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false